### ISSUE TITLE
Formatting sub-documents

### ISSUE THREAD

**Issue by mescobal** [dohliam/asciidoc-kate#3]
Hi: I have a master document that includes "sub-documents". The syntax highlighting only works if the document begins with "Level" 1:
= Titile of the document

but my "sub-documents" begin with level 2

== Chapetr

and the syntax hightlighting does not work.

I know the thread is old but... just in case

**Comment by dohliam** [comment]
Hi @mescobal thanks for the feedback! In case you are not already aware, recent versions of Kate and Kwrite now have built-in (and much nicer) support for AsciiDoc highlighting, so there's no need to install this highlighter separately anymore.

However, I just tried using the "sub-document" format you were talking about and you are right that the in-built highlighter does not seem to pick it up. I would suggest filing this as a bug with the Kate project.

In the meantime, you have reminded me that I should add a note to the Readme about the support for AsciiDoc in Kate now! :smile:

**Comment by mescobal** [comment]
The Linux community is amazing!!!! The speed of the response is
incredible!!!!!
Thanks a lot!!!!

Marcelo
